### ISSUE TITLE
Incorrect CV file

### ISSUE THREAD

**Issue by GRF-Sunomikp31** [ZH-Mao/Direct-3D-Ultrasound-Fusion-for-TEE-Winter-School#1]
Hi，Zhehua，I think you give a Incorrect CV file in your github：https://github.com/ZH-Mao/ZH-Mao.github.io/blob/dev/files/CV.pdf
That repo can't bring up issues, so let me remind you here
By the way，I also graduated from HFUT!

**Comment by ZH-Mao** [comment]
> Hi，Zhehua，I think you give a Incorrect CV file in your github：https://github.com/ZH-Mao/ZH-Mao.github.io/blob/dev/files/CV.pdf That repo can't bring up issues, so let me remind you here By the way，I also graduated from HFUT!

Hi Dong Li, thank you so much for your kind reminder! Really nice to meet you!  :D

**Comment by GRF-Sunomikp31** [comment]
Do you use wechat? and Can I add you wechat?

**Comment by ZH-Mao** [comment]
> Do you use wechat? and Can I add you wechat?

Yes, sure. I have sent you my WeChat through your foxtail. :D

**Comment by GRF-Sunomikp31** [comment]
I will add！
